branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dist: bionic
      language: python
      python: "3.6"
    - os: linux
      dist: bionic
      language: python
      python: "3.7"
    - os: linux
      dist: xenial
      language: python
      python: "3.6"
    - os: linux
      dist: xenial
      language: python
      python: "3.7"
    - os: osx
      osx_image: xcode11.2
      language: shell

install:
  - pip3 install virtualenv
  - virtualenv devenv
  - source devenv/bin/activate
  - pip3 install -r requirements.txt
  - pre-commit install

script:
  - pre-commit run --all-files
  - pytest .

notifications:
  email:
    recipients:
      - roman.s@p2p.org
    on_success: never
    on_failure: always
