# Multicall default settings settings
MULTICALL_MAX_BUNCH: int = 275
MULTICALL_MAX_WORKERS: int = 6
MULTICALL_MAX_RETRIES: int = 5
MULTICALL_POOL_EXECUTOR_TIMEOUT: int = 30
VALIDATE_POOL_EXECUTOR_TIMEOUT: int = 10
